bj_project/AboutUs/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include, url 
from django.views.generic import ListView
import jepropose.views
from jerecherche.models import Student_propose, Student_recherche, Nature, Lending
import AboutUs.views


app_name='AboutUs'
urlpatterns = [    
    url(r'^$', AboutUs.views.page_aboutus, name='page_aboutus'),
    ]

bj_project/bj_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls import include, url 
import jerecherche.views
import jepropose.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jepropose/', include('jepropose.urls', namespace='jepropose')),
    path('AboutUs/', include('AboutUs.urls', namespace='AboutUs')),
    url(r'^$', jerecherche.views.index),
    url(r'^jerecherche/', include('jerecherche.urls', namespace="jerecherche")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

bj_project/jepropose/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include, url 
from django.views.generic import ListView
import jepropose.views
from jerecherche.models import Student_propose, Student_recherche, Nature, Lending

app_name='jepropose'
urlpatterns = [    
    url(r'^$', jepropose.views.page_jepropose, name='page_jepropose'),
    ]

bj_project/jepropose/forms.py
from django import forms

class ProposingForm(forms.Form):
    name = forms.CharField(
        label='Nom',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True)
    mail = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        required=True)
    nature = forms.CharField(
        label='Nature du produit',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True)

bj_project/jepropose/views.py
from django.shortcuts import render
from django.http import HttpResponse
from jerecherche.models import Student_propose, Student_recherche, Nature, Lending
from jepropose.forms import ProposingForm
from django import forms
from django.views.generic import FormView


def page_jepropose(request):
    """Cette fonction permet d'afficher la page je propose qui permet à tous les étudiants de proposer sur le site les objets qu'ils souhaitent prêter.
    Dans un premier temps, la fonction recueille les données que l'utilisateur rentre (mail,nom,nature)
    puis si l'utilisateur n'est pas encore rentré dans la base de donnée, la fonction l'ajoute.
    De même si l'objet n'existe pas encore(n'a jamais été proposé) on l'ajoute à la table.
    Enfin on ouvre la page qui remercie un utilisateur qui a proposé un objet. """
    context={}    
    if request.method == 'POST':
        form = ProposingForm(request.POST)
        if form.is_valid():
            mail = form.cleaned_data['mail']
            name = form.cleaned_data['name']
            nature=form.cleaned_data['nature']

            studentp = Student_propose.objects.filter(mail=mail)
            if not studentp.exists():
                # Si l'étudiant n'est pas dans la base de données on l'ajoute à celle-ci
                studentp = Student_propose.objects.create(
                    mail=mail,
                    name=name,
                )
            else:
                studentp = studentp.first()

            newobject = Nature.objects.filter(name=nature)
            if not newobject.exists():
                # Si l'objet n'existe pas on l'ajoute à la table
                newobject = Nature.objects.create(name=nature, students=studentp)

            else:
                newobject = newobject.first()

            context = {
                'product_name': newobject.name
            }
            return render(request, 'jepropose/merci.html', context)
        else:
            # Si le format n'est pas celui attendu
            # Renvoie une erreur dans ce cas
            context['errors'] = form.errors.items()
    else:
        form = ProposingForm()
    context['form'] = form
    return render(request, 'jepropose/listing.html', context)

bj_project/jepropose/templates/jepropose/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'jepropose/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'jepropose/css/business-casual.css' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="brand"><a href="/">TRO-CS</a></div>
    <div class="address-bar">CentraleSupélec campus de Gif</div>

    <div class="container">
      <div class="row">
        <div class="box">
                {% block content %}{% endblock %}
            </div>
          </div>
        </div>
    
        <!-- jQuery -->
        <script src="{% static 'jepropose/static/js/jquery.js' %}"></script>
    
        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'jepropose/static/js/bootstrap.min.js' %}"></script>
    
      </body>
    </html>

bj_project/jepropose/templates/jepropose/listing.html
{% extends 'jepropose/base.html' %}

{% block content %}

<hr>
<center><h1 class="intro-text text-center">Que proposez-vous?</h1></center>
<hr>
  <h2 class="text-center">Produit à proposer:</h2>
  <p style="margin-bottom: 20px;">Renseignez les cases suivantes pour proposer un produit! </p>
  <form class="form-inline" action="{% url 'jepropose:page_jepropose' %}" method="post">
      {% csrf_token %}

    <div class="form-group">
      <label for="name" class="control-label">Nom</label>
      <input type="text" name="name" value="" id="name">
    </div>
    <div class="form-group">
      <label for="mail" class="control-label">E-mail</label>
      <input type="text" name="mail" value="" id="mail">
    </div>
    <div class="form-group">
        <label for="nature" class="control-label">Nature du produit</label>
        <input type="text" name="nature" value="" id="nature">
      </div>

    <!-- <input type="hidden" class="hidden" value="" name="product_id"> -->

    <button type="submit" class="btn btn-success">Envoyer</button>
  </form>

</div>


{% endblock %}

bj_project/jepropose/templates/jepropose/merci.html
{% extends 'jepropose/base.html' %}

{% block content %}

    <hr>
    <center><h1 class="intro-text text-center"> Merci !</h1></center>
    <hr>
    <center><p>Vous venez de proposer le produit : <b>{{product_name}} </b> à l'échange.</p></center>
    <hr>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ULKL09NAih8" frameborder="0" allowfullscreen></iframe>
    </div>

{% endblock %}