bj_project/AboutUs/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include, url 
from django.views.generic import ListView
import jepropose.views
from jerecherche.models import Student_propose, Student_recherche, Nature, Lending
import AboutUs.views


app_name='AboutUs'
urlpatterns = [    
    url(r'^$', AboutUs.views.page_aboutus, name='page_aboutus'),
    ]

bj_project/bj_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls import include, url 
import jerecherche.views
import jepropose.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jepropose/', include('jepropose.urls', namespace='jepropose')),
    path('AboutUs/', include('AboutUs.urls', namespace='AboutUs')),
    url(r'^$', jerecherche.views.index),
    url(r'^jerecherche/', include('jerecherche.urls', namespace="jerecherche")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

bj_project/jerecherche/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include, url 
from django.views.generic import ListView
import jerecherche.views
from jerecherche.models import Student_propose, Student_recherche, Nature, Lending

app_name='jerecherche'
urlpatterns = [    
    url(r'^$', jerecherche.views.liste_jerecherche, name='liste_jerecherche'),
    url(r'^(?P<product_id>[0-9]+)/$', jerecherche.views.description_jerecherche, name='description_jerecherche'),
    url(r'^search/$', jerecherche.views.search_jerecherche, name='search_jerecherche'),
]

bj_project/jerecherche/models.py
from django.db import models
import datetime
from django.utils import timezone


class Student_propose(models.Model):
    name = models.CharField(max_length=40)
    mail = models.EmailField()
    
    def __str__(self):
        return self.name

class Student_recherche(models.Model):
    name = models.CharField(max_length=40)
    mail = models.EmailField()

    def __str__(self):
        return self.name

class Nature(models.Model):
    name = models.CharField(max_length=40)
    available = models.BooleanField(default=True)
    picture = models.TextField(default=True)
    students = models.ManyToManyField(Student_propose, related_name='products', blank=True)
    
    def __str__(self):
        return self.name

class Lending(models.Model):
    duree = models.DateTimeField(auto_now_add=True)
    contacte = models.BooleanField(default=False)
    product = models.OneToOneField(Nature,on_delete=models.CASCADE)
    liaison = models.ForeignKey(Student_recherche, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.duree)

bj_project/jerecherche/forms.py
from django import forms

class LendingForm(forms.Form):
    name = forms.CharField(
        label='Nom',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True
        )
    mail = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        required=True)

bj_project/jerecherche/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.template import RequestContext
from django.http import HttpResponse
from django.db import IntegrityError, transaction
from jerecherche.models import Student_propose, Student_recherche, Nature, Lending
from jerecherche.forms import LendingForm

def index(request):
    """ permet d'accéder au template index"""
    return render_to_response("jerecherche/index.html")

def liste_jerecherche(request):
    """
    Affiche tous les produits proposés à l’échange
    """
    products = Nature.objects.all()
    context = {
        'products': products
    }
    return render(request, 'jerecherche/listing.html', context)

@transaction.atomic
def description_jerecherche(request, product_id):
    """Prend en argument les données du formulaire. Ajoute les coordonnées d'un étudiant recherchant un objet dans la base de données
    si celui-ci n'y est pas encore. Affiche un message de confirmation de réservation si le produit 
    demandé est disponible. Renvoie un message d'erreur sinon."""
    product = get_object_or_404(Nature, pk=product_id)
    students_name=[producer.name for producer in product.students.all()]
    context = {
        'product_name': product.name,
        'students_name': students_name,
        'product_id': product.id,
        'thumbnail': product.picture
    }

    if request.method == 'POST':
        form = LendingForm(request.POST)
        if form.is_valid():
            mail = form.cleaned_data['mail']
            name = form.cleaned_data['name']
 
            try:
                with transaction.atomic():
                    studentr = Student_recherche.objects.filter(mail=mail)
                    if not studentr.exists():
                    # Ajoute un nouvel étudiant à la table s'il n'y est pas encore
                        studentr = Student_recherche.objects.create(
                            mail=mail,
                            name=name
                        )
                    else:
                        studentr = studentr.first()

                    product = get_object_or_404(Nature, id=product_id)
                    lending = Lending.objects.create(
                        liaison=studentr,
                        product=product
                    )
                    product.available = False
                    product.save()
                    context = {
                        'product_name': product.name
                    }
                    return render(request, 'jerecherche/merci.html', context)
            except IntegrityError:
                form.errors['internal'] = "Oups ! Vous avez déjà réservé cet objet."
    
    else:
        # N'accepte pas les données au mauvais format
        # Ajoute les erreurs au template
        form = LendingForm()
    context['form'] = form
    context['errors'] = form.errors.items()
    return render(request, 'jerecherche/detail.html', context) #renvoie à une page de confirmation de réservation d'un objet


def search_jerecherche(request):
    """Affiche les étudiants qui proposent un objet si celui-ci est disponible"""
    query = request.GET.get('query')
    if not query:
        products = Nature.objects.all()
    else:
        products = Nature.objects.filter(name__icontains=query)

    if not products.exists():
        products = Nature.objects.filter(students__name__icontains=query)
    title = "Résultats pour la requête %s"%query
    context = {
        'products': products,
        'name': Student_propose.name
    }
    return render(request, 'jerecherche/search.html', context)

bj_project/jerecherche/templates/jerecherche/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'jerecherche/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'jerecherche/css/business-casual.css' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="brand"><a href="/">TRO-CS</a></div>
    <div class="address-bar">CentraleSupélec campus de Gif</div>

    <div class="container">
      <div class="row">
        <div class="box">
                {% block content %}{% endblock %}
            </div>
          </div>
        </div>
    
        <!-- jQuery -->
        <script src="{% static 'jerecherche/static/js/jquery.js' %}"></script>
    
        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'jerecherche/static/js/bootstrap.min.js' %}"></script>
    
      </body>
    </html>

bj_project/jerecherche/templates/jerecherche/detail.html
{% extends 'jerecherche/base.html' %}

{% block content %}
<hr>
<center><h1 class="intro-text text-center">{{ product_name }}</h1></center>
<hr>
<div class="col-md-6">
  <img width="200px" src="{{ thumbnail }}" alt="{{ product_name }}" class="img-responsive" align=middle >
</div>
<div class="col-md-6">
  <div style="margin-bottom:45px; margin-left: 80px">
    <h2 class="text-center students_name">Etudiant proposant ce produit</h2>
    {% for student in students_name %}
      <li>{{student}}</li>
    {% endfor %}
  </div>

  <h2 class="text-center students_name" style="margin-left: 80px;"> Réserver le produit : {{ product_name }}</h2>
  <p style="margin-bottom: 30px; margin-left: 80px; ">Demandez-nous de mettre de côté le produit <strong>{{ product_name }}</strong> puis venez le chercher dès que possible chez l'étudiant ! </p>
  <form class="form-inline" action="{% url 'jerecherche:description_jerecherche' product_id=product_id %}" method="post">
      {% csrf_token %}

    <div class="form-group {% if form.name.errors %}has-warning has-feedback{% endif %}" style="margin-left: 80px;">
      <label for="name" class="control-label">Nom</label>
      <input type="text" name="name" value="" id="name">

    </div>
    <div class="form-group {% if form.email.errors %}has-warning has-feedback{% endif %}" style="margin-left: 80px;">
      <label for="mail" class="control-label">E-mail</label>
      <input type="text" name="mail" value="" id="mail">

    </div>

    <!-- <input type="hidden" class="hidden" value="" name="product_id"> -->

    <button type="submit" class="btn btn-success" style="margin-left: 90px;">Réserver</button>
    
    {% if errors %}
  <div>
    {% for key, error in errors %}
    {% autoescape off %}
      {{ error }}
    {% endautoescape %}
    {% endfor %}
  </div>
  {% endif %}

</div>

{% endblock %}

bj_project/jerecherche/templates/jerecherche/index.html
<!DOCTYPE html>

<html>
<head>
	{% load static %}
	<meta charset="UTF-8" />
	<title>TRO-CS</title>
	<link rel="stylesheet" href="{% static 'jerecherche/css/style.css' %} " type="text/css">
</head>
<body>
	{% load static %}
	<div id="header">
		<div>
			<div id="logo">
				<a href="index.html">
			</div>
			<div id="navigation">
				<div>
					<ul>
						<li class="current"><a href="http://127.0.0.1:8000/">   Home   </a></li>
						<li><a href="http://127.0.0.1:8000/AboutUs/">   About Us   </a></li>
						<li><a href="http://127.0.0.1:8000/jerecherche/">   Je recherche   </a></li>
						<li><a href="http://127.0.0.1:8000/jepropose/">   Je propose   </a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div id="content">
		<div id="section">
			<div>
				<br><h1>TRO-CS friendly !</h1>
				<br><p> <b>Principe du site </b> : six étudiants de CentraleSupélec ont créé pour toi un site de troc. Que tu cherches un balai un lendemain de soirée difficile ou que tu souhaites simplement te débarasser d'un meuble encombrant, ce site est fait pour toi !  </p>
				<span>
					<br><a class="first" href="http://127.0.0.1:8000/jerecherche/">Réserve un objet</a>
					<a href="http://127.0.0.1:8000/jepropose/"> Propose un objet <!DOCTYPE html>
					<html lang="en">
					<head>
						<meta charset="UTF-8">
						<meta name="viewport" content="width=device-width, initial-scale=1.0">
						<meta http-equiv="X-UA-Compatible" content="ie=edge">
						<title>Document</title>
					</head>
					<body>
						
					</body>
					</html><!DOCTYPE html>
					<html lang="en">
					<head>
						<meta charset="UTF-8">
						<meta name="viewport" content="width=device-width, initial-scale=1.0">
						<meta http-equiv="X-UA-Compatible" content="ie=edge">
						<title>Document</title>
					</head>
					<body>
						
					</body>
					</html></a>
				</span>
			</div>
			<div id="figure">
				<iframe src="https://www.youtube.com/embed/ULKL09NAih8" width="650" height="300"></iframe>
				<span></span>
			</div>
			<span class="background"></span>
		</div>
		<div id="featured">
			<ul>
				<li class="first">
					<a href="http://127.0.0.1:8000/jerecherche/"><img width="280x" height="150"  src="{% static 'jerecherche/images/troc-cuturel-télérama.jpg' %}" alt="Image" /></a>
					<span></span>
					<p align="justify">Tu recherches un appareil à raclette pour tes soirées hivernales, une raquette de tennis pour jouer avec un pote ? Check vite les propositions !</p>
					<a class="link" href="http://127.0.0.1:8000/jerecherche/">Je recherche</a>
				</li>
				<li>
					<a href="http://127.0.0.1:8000/jepropose/">
					<span></span><img width="280x" height="150" src="{% static 'jerecherche/images/17cb14caa658314182e65f8d6c91bda1.jpg' %}" alt="Image" /></a>
					<p align="justify">Tes placards sont bourrés à craquer, tu aimerais que d’autres puissent profiter d’objets que tu n’utilises que rarement, propose ici tes objets !</p>
					<a class="link" href="http://127.0.0.1:8000/jepropose/">Je propose</a>
				</li>
				<li>
					<a href="http://127.0.0.1:8000/AboutUs/"><img width="280x" height="150" src="{% static 'jerecherche/images/logo.jpg' %}" alt="Image" /></a>
					<span></span>
					<p style="padding-bottom: 45px" align="justify">Apprends-en plus sur nous ici</p>                                                                                                                   </p>
					<a class="link" href="http://127.0.0.1:8000/AboutUs/">About Us</a>
				</li>
			</ul>
		</div>
	</div>
	<div id="footer">
		<div>
			<div class="first">
						<div>
					<p>Telephone. : <span>0666666666</span></p>
					<p>Email : <span>prenom.nom@student-cs.fr</span></p>
				</div>
			</div>
			<div>
				<h3>Get Social with us!</h3>
				<p>Check our pages</p>
				<div>
					<a href="https://www.facebook.com/centralesupelec/" class="facebook" target="_blank"></a>
					<a href="http://twitter.com/centralesupelec" class="twitter" target="_blank"></a>

				</div>
			</div>
			<div>
				<h3>Share your thoughts!</h3>
				<form action="#">
					<label for="subscribe"><input type="text" id="subscribe" maxlength="30" value="email address" /></label>
					<input class="submit" type="submit" value="" />
				</form>
				<p>Copyright &copy; 2018 TRO-CS Incorporated <br /> All rights reserved</p>
			</div>
		</div>
	</div>
</body>
</html> 

bj_project/jerecherche/templates/jerecherche/indexjerecherche.html
{% extends 'jerecherche/base.html' %}


{% block content %}

  {% include 'jerecherche/list.html' with list_title='Nos derniers produits' %}

{% endblock %}

bj_project/jerecherche/templates/jerecherche/list.html
<div class="col-lg-12">
    <hr>
    <center><h2 class="intro-text text-center">{{ list_title }}
    </h2></center>
    <hr>
</div>
<br>

<center>{% include 'jerecherche/search_form.html' %}</center>
<br>
<br>

{% if products|length_is:"0" %}
    <div class="text-center">
    <br>
    <br>
      Nous n'avons trouvé aucun résultat à cette requête. 
      Cherchez un autre produit !
    </div>

{% else %}
    {% for product in products %}
        <div class="col-sm-4 text-center">
            <a href="{% url 'jerecherche:description_jerecherche' product_id=product.id %}">
              <img class="img-responsive" width="100px" src="{{ product.picture }}" alt="{{ product.name }}">
            </a>
            <h3><a href="{% url 'jerecherche:description_jerecherche' product_id=product.id %}">{{ product.name }}</a></h3>
        </div>
        {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
    {% endfor %}

{% endif %}

bj_project/jerecherche/templates/jerecherche/listing.html
{% extends 'jerecherche/base.html' %}

{% block content %}

    {% include 'jerecherche/list.html' with list_title='Tous nos produits disponibles' %}

{% endblock %}

bj_project/jerecherche/templates/jerecherche/merci.html
{% extends 'jerecherche/base.html' %}

{% block content %}

    <hr>
    <center><h1 class="intro-text text-center"> Merci !</h1></center>
    <hr>
    <center><p>Le produit <b>{{ product_name }}</b> vient d'être réservé.</p></center>
    <hr>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ULKL09NAih8" frameborder="0" allowfullscreen></iframe>
    </div>

{% endblock %}

bj_project/jerecherche/templates/jerecherche/search.html
{% extends 'jerecherche/base.html' %}

{% block content %}

    {% include 'jerecherche/list.html' with list_title='Voici le produit demandé' %}

{% endblock %}

bj_project/jerecherche/templates/jerecherche/search_form.html
<div class="col-lg-12 detail-separator">
          <form class="col-md-6 col-md-offset-3 text-center" action="{% url 'jerecherche:search_jerecherche' %}" method="get" accept-charset="utf-8">
          <div class="form-group">
            <b><label for="searchForm">Trouvez votre produit</label></b>
            <br /><input id="searchForm" class="form-control" name="query">
          </div>
          <style type='text/css'>
          .form-control { 
            width: 60%; 
            } 
          </style>
          <span class="help-block" id="helpBlock">Taper le type de produit recherché. </span>
        </form>
      </div>